Add function call request param
64bit/async-openai pull request #79
Opened 2023-06-19 14:25 UTC by DaviRain-Su

2023-06-20 05:03 UTC, b0xtch approved these changes

2023-06-20 05:09 UTC, b0xtch commented
I would also update the readme to add function as feature

2023-06-20 09:37 UTC, DaviRain-Su commented
I am currently writing an example code for function calls, but I encountered an issue with the error: `JSONDeserialize(Error("invalid type: null, expected a string", line: 11, column: 23)).`  I need some help to resolve this.

2023-06-21 05:51 UTC, 64bit commented
Hi @DaviRain-Su, Thank you for the PR and adding example for this new feature - its a great way to test it.

Here are some hints for you to debug this further:
- see the updated upstream OpenAPI spec and match it with Rust type in code
- setup tracing_subscriber so that `tracing::error!( ... )` can log the actualy json payload causing deserializtion error. `examples/rate-limit-completions` has an example - however you might need to change log level. 

Hope this helps

2023-06-21 06:41 UTC, DaviRain-Su commented
Successfully added an example that can use function calls.

2023-06-23 23:16 UTC, 64bit requested changes
It appears that naming does not adheres to OpenAPI spec.

For example  `ChatCompletionFunctions` , Please see the names of new types in this PR https://github.com/64bit/async-openai/pull/73


For background: all types in `types.rs` are named based on OpenAPI component schema.

2023-06-23 23:16 UTC, 64bit commented on async-openai/src/types/types.rs
> +    pub content: Option<String>,
Comment needs to be updated (please see latest spec)

> The contents of the message. `content` is required for all messages except assistant messages with function calls.

2023-06-24 05:12 UTC, DaviRain-Su commented
Have fix all.

2023-06-24 17:00 UTC, 64bit commented
`function_call` in `ChatCompletionRequestMessage` and `ChatCompletionResponseMessage` can also be a struct with `name` and `arguments` - I'll take care of it before publishing.

Thank you for addressing the comments,  nice work on the new example!

2023-06-24 17:01 UTC, 64bit approved these changes

2023-06-24 17:01 UTC, merged

2023-06-24 18:05 UTC, 64bit commented
This is released in v0.12.0